import type { ProviderProfile } from "./types";

export const providerDirectory: ProviderProfile[] = [
  {
    id: "med-001",
    name: "Avery Primary Care",
    kind: "doctor",
    specialty: "Family Medicine",
    services: ["annual physical", "primary care", "vaccinations", "blood pressure", "diabetes care"],
    address: "1120 Mission St",
    city: "San Francisco",
    state: "CA",
    postalCode: "94103",
    latitude: 37.7771,
    longitude: -122.4128,
    distanceMilesFromSampleCenter: 1.4,
    phone: "(415) 555-0134",
    website: "https://example.com/avery-primary-care",
    insuranceAccepted: ["Aetna", "Blue Cross", "Cigna", "Medicare"],
    acceptingNewPatients: true,
    languages: ["English", "Spanish"],
    accessibility: ["wheelchair access", "elevator", "accessible restroom"],
    telehealth: true,
    nextAvailable: "2026-07-02",
    rating: 4.7,
    reviewCount: 184,
    notes: "Good fit for preventive care and chronic condition management.",
  },
  {
    id: "med-002",
    name: "Bay Cardiology Group",
    kind: "doctor",
    specialty: "Cardiology",
    services: ["cardiology consult", "chest pain evaluation", "echocardiogram", "heart rhythm"],
    address: "301 Battery St",
    city: "San Francisco",
    state: "CA",
    postalCode: "94111",
    latitude: 37.7947,
    longitude: -122.4002,
    distanceMilesFromSampleCenter: 2.8,
    phone: "(415) 555-0188",
    website: "https://example.com/bay-cardiology",
    insuranceAccepted: ["Blue Cross", "UnitedHealthcare", "Medicare"],
    acceptingNewPatients: true,
    languages: ["English", "Mandarin"],
    accessibility: ["wheelchair access", "parking validation"],
    telehealth: false,
    nextAvailable: "2026-07-08",
    rating: 4.6,
    reviewCount: 96,
    notes: "Specialist office; referral may be required depending on insurance.",
  },
  {
    id: "med-003",
    name: "Noe Valley Dermatology",
    kind: "doctor",
    specialty: "Dermatology",
    services: ["skin cancer screening", "rash", "acne", "mole check", "eczema"],
    address: "3985 24th St",
    city: "San Francisco",
    state: "CA",
    postalCode: "94114",
    latitude: 37.7515,
    longitude: -122.431,
    distanceMilesFromSampleCenter: 3.9,
    phone: "(415) 555-0119",
    website: "https://example.com/noe-derm",
    insuranceAccepted: ["Aetna", "Cigna", "Kaiser PPO"],
    acceptingNewPatients: false,
    languages: ["English"],
    accessibility: ["wheelchair access"],
    telehealth: true,
    nextAvailable: "2026-08-15",
    rating: 4.8,
    reviewCount: 221,
    notes: "Strong reviews, but not currently accepting new patients.",
  },
  {
    id: "den-001",
    name: "Market Street Dental Studio",
    kind: "dentist",
    specialty: "General Dentistry",
    services: ["cleaning", "exam", "x-ray", "fillings", "teeth whitening"],
    address: "865 Market St",
    city: "San Francisco",
    state: "CA",
    postalCode: "94103",
    latitude: 37.7842,
    longitude: -122.4063,
    distanceMilesFromSampleCenter: 0.8,
    phone: "(415) 555-0101",
    website: "https://example.com/market-dental",
    insuranceAccepted: ["Delta Dental", "MetLife", "Cigna Dental"],
    acceptingNewPatients: true,
    languages: ["English", "Spanish", "Tagalog"],
    accessibility: ["wheelchair access", "near transit"],
    telehealth: false,
    nextAvailable: "2026-07-01",
    rating: 4.9,
    reviewCount: 312,
    notes: "Best sample match for routine dental care near downtown.",
  },
  {
    id: "den-002",
    name: "Pacific Endodontics",
    kind: "dentist",
    specialty: "Endodontics",
    services: ["root canal", "tooth pain", "endodontic retreatment", "cracked tooth"],
    address: "2100 Webster St",
    city: "San Francisco",
    state: "CA",
    postalCode: "94115",
    latitude: 37.7891,
    longitude: -122.4338,
    distanceMilesFromSampleCenter: 3.2,
    phone: "(415) 555-0145",
    website: "https://example.com/pacific-endo",
    insuranceAccepted: ["Delta Dental", "Guardian", "Aetna Dental"],
    acceptingNewPatients: true,
    languages: ["English", "Korean"],
    accessibility: ["wheelchair access", "accessible parking"],
    telehealth: false,
    nextAvailable: "2026-07-03",
    rating: 4.7,
    reviewCount: 88,
    notes: "Specialty dental office for urgent tooth pain and root-canal needs.",
  },
  {
    id: "den-003",
    name: "Sunset Pediatric Dentistry",
    kind: "dentist",
    specialty: "Pediatric Dentistry",
    services: ["child dental exam", "sealants", "cleaning", "cavity care", "sedation dentistry"],
    address: "1701 Noriega St",
    city: "San Francisco",
    state: "CA",
    postalCode: "94122",
    latitude: 37.7531,
    longitude: -122.4819,
    distanceMilesFromSampleCenter: 6.4,
    phone: "(415) 555-0197",
    website: "https://example.com/sunset-pediatric-dentistry",
    insuranceAccepted: ["Delta Dental", "MetLife", "Medi-Cal Dental"],
    acceptingNewPatients: true,
    languages: ["English", "Cantonese", "Spanish"],
    accessibility: ["wheelchair access", "sensory-friendly visits"],
    telehealth: false,
    nextAvailable: "2026-07-10",
    rating: 4.8,
    reviewCount: 145,
    notes: "Child-focused environment and sensory-friendly appointment options.",
  },
];
